name: Deploy To EC2 via SSH ci/cd 4

on:
  push:
    branches: [ "main" ]   # or master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Copy files to EC2
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.HOST_DNS }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "."
        target: "${{ secrets.TARGET_DIR }}"

    - name: Run SSH Commands
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.HOST_DNS }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd ${{ secrets.TARGET_DIR }}
          sudo docker-compose down
          sudo docker-compose build --no-cache
          sudo docker-compose up -d
